### ISSUE TITLE
mcppb20: psihat is different from expected - order seems wrong

### ISSUE THREAD

**Issue by eler20** [nicebread/WRS#11]
Hi, 
I applied mcppb20 (actually from WRS2) to my data, getting other psihats than expected. Therefore, I wanted to replicate the example for mcppb20 from Field and Wilcox's paper (https://www.sciencedirect.com/science/article/pii/S0005796717301067) using the kellyetalz.csv. 
I applied mcppb20 and did get the same results as shown in the paper, but I wanted to understand psihat better and "manually" calculated psihats using mean(x, tr = 0.2), see below. To be able to compare the results, I removed the bootstrapping from mcppb20. 
```
WRS2::mcppb20(z ~ Intervention,  data = fbqOnly, tr = 0.2)

pos <- subset(fbqOnly, Intervention == "Positive Information")
modell <- subset(fbqOnly, Intervention == "Non-Anxious Modelling")
no <- subset(fbqOnly, Intervention == "No Intervention")

mean(modell$z, tr = 0.2) - mean(pos$z, tr = 0.2) # result = 1.01
mean(no$z, tr = 0.2) - mean(pos$z, tr = 0.2)  # result = 1.39
mean(no$z, tr = 0.2) - mean(modell$z, tr = 0.2) # result = 0.38
```
So manually calculated, only the positive information vs. no intervention has the correct result for psihat. The other two psihats seem to be assigned to the wrong comparison.

Have you noted this behavior before or have I made a mistake in reasoning?
Thank you in advance!

**Comment by nicebread** [comment]
Hi, please send such inquiries to Rand Wilcox: https://dornsife.usc.edu/cf/labs/wilcox/wilcox-faculty-display.cfm
