### ISSUE TITLE
parallel package installation

### ISSUE THREAD

**Issue by bigpas** [nicebread/WRS#3]
Hi, 

the "parallel" package is listed among the "suggested" packages for WRS.

Starting from R 2.14.0 (2011), 
"parallel" is shipped together with R.
Thus, it does require any installation 
(btw, an installation attempt will issue a "Warning"
```
package ‘parallel’ is not available (for R version x.x.x)
```
), 
just 

```
require(parallel)
```
or 
```
library(parallel)
```
is enough! 

best,

**Comment by nicebread** [comment]
Thanks! Fixed.
