### ISSUE TITLE
Bug in mcp2a function?

### ISSUE THREAD

**Issue by stevensjo** [nicebread/WRS#4]
Hello,
I recently started using the WRS package for performing robust 2-way ANOVA. However, I seem unable to specify a custom contrast matrix that is used when I call mcp2a for performing multiple comparison using M-estimators. The functions just performs all the automatically generated contrasts. If I use the same contrast matrix in the function pbmcp, the correct contrasts are taken. Does this function actually performs the same as mcp2a if I define a custom contrast matrix? Thanks for your help. The package is great and I have learned a lot about robust testing.
Kind regards,
Jo Stevens

**Comment by rrwilcox** [comment]
Jo,

Use the R function linconm when specifying the contrast coefficients. Will modify mcp2a to print a message about this.  Let me know if any further problems come up.

Rand Wilcox
