### ISSUE TITLE
Error with outproad command: Object 'newgval' not found

### ISSUE THREAD

**Issue by jaminday** [nicebread/WRS#8]
I ran the following command on `my_data`, a dataframe with 354 rows and 27 variables:

    outproad(my_data, center = NA, plotit = FALSE, MM = TRUE, cop = 2, rate = 0.05, iter = 100)

After about 45mins of computation time, it stopped with the following error:

    Error in outpro(m, gval = newgval, center = center, plotit = TRUE, op = op,  :
        object 'newgval' not found

Any suggestions on this one?

**Comment by nicebread** [comment]
Sorry, I only convert Wilcox' files into a package. For all questions concerning the functions themselves, please contact R.R.Wilcox directly.
